id = "riverpod-snippets"
name = "Riverpod Snippets"
version = "0.0.1"
schema_version = 1
authors = ["Steeven Lopez <stee-ven_94@outlook.com>"]
description = "Collection of Riverpod snippets for Flutter/Dart development on the Zed editor."
repository = "https://github.com/OppositeDragon/riverpod-snippets"
snippets = "./snippets/dart.json"
